### PR TITLE
Added forgotten redirect/notFound fields into gsspWithNonce function

### PR DESCRIPTION
**Pull request by komw**
Function gsspWithNonce did not have the redirect/notFound fields added. This pull request adds these fields and also improves the test page (extracted links, added test pages to test redirect/notFound fields)."

### CODE REVIEW

**Comment by komw** [comment]
@nibtime Will you have time to look at this PR?

**Comment by wpodgorski** [comment]
Hey @nibtime! Any update on that? Can we have it merged some time soon please 🙏?

**Comment by miklosz** [comment]
Hmmm, this looks like a change I am also waiting for

**Comment by komw** [comment]
@nibtime any progress of that?

**Comment by komw** [comment]
@boennemann  are you able to merge this PR?

**Comment by komw** [comment]
@alexturpin @Neki @renet @benhodgson87 @Shamilik @DuCanhGH @aheimlich Guys, are you able to look at this PR?

**Pull request closed without merging**
